name: Lint
on:
  push:
    branches:
      - master
  pull_request:
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-go@v4
      with:
        go-version: 1.20.x
        check-latest: true
    - run: go mod tidy
    - run: go version
    - run: go fix ./...
    - run: go vet -all ./...
    - name: Run golangci-lint
      uses: golangci/golangci-lint-action@v3
      with:
        version: v1.54.2
        args: --max-same-issues 0 --max-issues-per-linter 0 --deadline=600s --fix
