name: Lint
on:
  push:
    branches:
      - master
  pull_request:
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-go@v4
      with:
        go-version: 1.20.x
        check-latest: true
    - run: go version
    - name: Run golangci-lint
      uses: golangci/golangci-lint-action@v3
      with:
        version: v1.54.2
        args:  --timeout 30m --enable=nolintlint,gochecknoinits,bodyclose,gofumpt,gocritic --verbose
